### ISSUE TITLE
Problem at the time to Parse JS in by providing URL

### ISSUE THREAD

**Issue by caffeinedoom** [nahamsec/JSParser#35]
Hi There!
I was trying to use JS Parser, everything worked fine until i tried to provide the url to parse

![Screen Shot 2020-05-15 at 12 40 42 PM](https://user-images.githubusercontent.com/42664605/82074878-68327c80-96a9-11ea-8f5f-ed160f726f52.png)

Then, Checking my terminal I got the following error. 

![Screen Shot 2020-05-15 at 12 43 05 PM](https://user-images.githubusercontent.com/42664605/82075057-a5970a00-96a9-11ea-9b13-7a491dfc3c0a.png)

I tried the same process on my VPS running debian, and my macbook. I'd appreciate if somebody can help me here. My googling skills didn't work this time :(

**Comment by tamjid0x01** [comment]
hey @CoffeeJunkiee , I'm using python 2.7 it's  work well .
so u can try wth python 2.7 ..
thanks

**Comment by caffeinedoom** [comment]
> hey @CoffeeJunkiee , I'm using python 2.7 it's work well .
> so u can try wth python 2.7 ..
> thanks

Thank you for your answer! Unfortunately still getting errors ! 
![Screen Shot 2020-05-17 at 3 28 33 PM](https://user-images.githubusercontent.com/42664605/82158025-1299d380-9853-11ea-8e43-2421c7e742a8.png)

**Comment by tamjid0x01** [comment]
![image](https://user-images.githubusercontent.com/45327979/82158398-7353fb00-98a9-11ea-980b-0a8540b17f1f.png)

hey @CoffeeJunkiee ,  $ python2 handler.py

**Comment by caffeinedoom** [comment]
Can you send an example with the input please?

**Comment by tamjid0x01** [comment]
> 
> 
> Can you send an example with the input please?

What is your current OS?

**Comment by caffeinedoom** [comment]
> > Can you send an example with the input please?
> 
> What is your current OS?

I'm currently using Mac OS catalina, and my VPS is using Kali Linux. Something that I've been looking at are my libraries. I'm using python 3.8, and I have python 2.7 
By using python 2.7 I have the following error
![Screen Shot 2020-05-19 at 12 08 00 PM](https://user-images.githubusercontent.com/42664605/82350466-64fd0080-99c9-11ea-9e0d-2a482fa8e884.png)
 
`Traceback (most recent call last):
  File "handler.py", line 2, in <module>
    import tornado.ioloop, tornado.web, tornado.autoreload
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.4-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 67
    def fileno(self) -> int:
                     ^
SyntaxError: invalid syntax`

**Comment by caffeinedoom** [comment]
Found the solution! Check python libraries.
